### ISSUE TITLE
Add support for get_search_folder_request

### ISSUE THREAD

**Issue by jdinunzio** [ilgarm/pyzimbra#1]
Hello,

I would like to extend pyzimbra to support another zimbra calls, like get_search_folder_request, but I'm having troubles intercepting the response for parse it. I tried to add a new dict to ZimbraSOAPParser:

'GetFolderResponse': {
                    'folder': {
                        'id':{},
                        'name':{},
                        'absFolderPath':{},
                        'folder':{}
                    },

but without success. I was wondering if you could give me a hit of what do I need to do to add a parser for a new response.

Thanks in advance.

**Comment by ilgarm** [comment]
Hi José,

Did you have a look at client/sample/get_account.py code? It probably should be possible to execute that request in the form:

``` python
res = zclient.invoke(zconstant.NS_ZIMBRA_ADMIN_URL,
                         sconstant.GetFolderRequest,
                         params)
```

just make sure you add a constant: sconstant.GetFolderRequest and pass right params to zclient for this request, and also check if this request goes to admin api or normal one.

I did not try this myself, so let me know if that helps or not. I do not have instance of zimbra at the moment to test this, and also last time I touched this code was 3 years ago.
